import { type I18nData, type Tab, type HabitFrequency } from './types';

export const DM_USERS_KEY = 'dm_users_v1';
export const DM_CURRENT_USER_KEY = 'dm_current_user_v1';

export const TABS: Tab[] = [
  {id:'daily',icon:'☀️',labelKey:'daily'},
  {id:'weekly',icon:'📅',labelKey:'weekly'},
  {id:'monthly',icon:'🗓️',labelKey:'monthly'},
  {id:'yearly',icon:'📆',labelKey:'yearly'},
  {id:'special',icon:'⭐',labelKey:'special'},
];

export const I18N: I18nData = {
  id:{
    enableReminders:"Aktifkan Pengingat", addHabit:"Tambah Amalan", export:"Ekspor", import:"Impor",
    todayProgress:"Progres Hari Ini", view:"Tampilan", tips:"Tips",
    tipText:"Kelompokkan amalan ke dalam kategori agar fokus. Klik bab di direktori untuk memfilter cepat.",
    checklist:"Checklist", name:"Nama", type:"Jenis", frequency:"Frekuensi", daily:"Harian", weekly:"Mingguan",
    monthly:"Bulanan", yearly:"Tahunan", special:"Khusus (tanggal tertentu)", reminderTime:"Jam Pengingat",
    reminderHint:"Izinkan notifikasi browser.", days:"Hari (Mingguan)", dayOfMonth:"Tanggal (Bulanan)",
    monthDay:"Bulan & Tanggal (Tahunan)", specificDates:"Tanggal Khusus", notes:"Catatan",
    save:"Simpan", saving:"Menyimpan...", noItems:"Belum ada amalan.", periodDaily:"Periode hari ini",
    periodWeekly:"Periode pekan ini (ISO Week)", periodMonthly:"Periode bulan ini", periodYearly:"Periode tahun ini",
    periodSpecial:"Tanggal khusus", edit:"Ubah", streak:"Rangkaian", best:"Terbaik",
    wajib: "Wajib", sunnah: "Sunnah", allCategories: "— Semua Kategori —",
    searchPlaceholder: "Cari / Search…", deleteConfirm: "Hapus amalan ini?",
    importSuccess: "Impor berhasil.", importFailed: "Impor gagal: ", invalidFile: "File tidak valid",
    remindersEnabled: "Pengingat aktif. Simpan tab ini tetap terbuka.", permissionDenied: "Izin notifikasi ditolak.",
    browserNotSupported: "Browser tidak mendukung Notification API.", modalTitleAdd: "Tambah Amalan", modalTitleEdit: "Ubah Amalan",
    categoryExample: "cth: Ibadah Ritual/Shalat atau Adab/Makan", subCategoryHint: "Gunakan “/” untuk sub-bab.",
    domExample: "Contoh: 1,15,30", datesExample: "YYYY-MM-DD; YY YY-MM-DD",
    notesPlaceholder: "Tambahkan niat, target, dalil/rujukan…", namePlaceholder: "Contoh: Shalat Subuh",
    directory: "Direktori (Bab & Adab)", directoryHint: "Gunakan format kategori bertingkat, contoh: Adab/Makan atau Rumah Tangga/Pernikahan.",
    history: "Riwayat", completionHistory: "Riwayat Penyelesaian", noCompletions: "Belum ada penyelesaian.", completedOn: "Selesai pada",
    targetStreak: "Target Rangkaian", reminders: "Pengingat", enableReminder: "Aktifkan pengingat untuk amalan ini",
    reminderDays: "Hari Pengingat", reminderDaysHint: "Biarkan kosong untuk semua hari.", allDays: "Setiap Hari", streakGoalReached: "Target Rangkaian Tercapai!",
    streakGoalReachedBody: "Selamat! Anda telah mencapai target rangkaian {target} hari untuk {habitName}.",
    theme: "Tema", light: "Terang", dark: "Gelap",
    editCategory: "Ubah Kategori", editCategoryPrompt: "Masukkan nama baru untuk '{oldPath}':",
    categoryRenameSuccess: "Kategori berhasil diubah.", categoryName: "Nama Kategori", other: "Lain-lain",
    otherFeatures: "Fitur Islami", quran: "Baca Quran", hadith: "Baca Hadits", zakat: "Kalkulator Zakat", prayerTimes: "Jadwal Sholat", qibla: "Arah Kiblat", duas: "Doa & Dzikir",
    editTitle: "Ubah Judul", saveContent: "Simpan Konten", editModule: "Ubah Modul", title: "Judul", content: "Konten",
    moduleContentPlaceholder: "Anda bisa menambahkan catatan, tautan, atau konten pribadi di sini...",
    analytics: "Analitik", progressDashboard: "Dasbor Progres", selectHabit: "Pilih Amalan untuk Dianalisis",
    overallProgress: "Progres Keseluruhan (Harian)", completionRateLast30Days: "Tingkat Penyelesaian (30 Hari Terakhir)",
    streakTrendLast30Days: "Tren Rangkaian (30 Hari Terakhir)", completions: "Penyelesaian",
    noDataForChart: "Data tidak cukup untuk menampilkan grafik.",
    analyticsInfo: "Analitik kini tersedia untuk semua frekuensi amalan.",
    timePeriod: "Jangka Waktu", last30Days: "30 Hari", last90Days: "90 Hari", last365Days: "1 Tahun",
    completionHeatmap: "Peta Kalender Penyelesaian", streakHistory: "Riwayat Rangkaian",
    streakLength: "Panjang Rangkaian", endedOn: "Berakhir pada", notCompleted: "Tidak Selesai",
    selectHabitFirst: "Pilih sebuah amalan untuk melihat detailnya.",
    due: "Jatuh Tempo", completed: "Selesai", missed: "Terlewat",
    contentSaved: "Konten disimpan!",
    useHijriCalendar: "Gunakan Kalender Hijriah", hijriBased: "Hijriah",
    dayOfMonthHijri: "Tanggal (Hijriah)", monthAndDayHijri: "Bulan & Tanggal (Hijriah)",
    monthHijri: "Bulan (Hijriah)",
    selectSurah: "Pilih Surat",
    loading: "Memuat...",
    errorFetching: "Gagal memuat data. Silakan coba lagi.",
    revelation_makkah: "Makkiyah",
    revelation_madinah: "Madaniyah",
    verses: "ayat",
    reminderDayOfMonth: "Tanggal Pengingat (Bulanan)",
    reminderMonthDay: "Bulan & Tanggal Pengingat (Tahunan)",
    backToList: "Kembali ke Daftar Surat",
    goTo: "Buka",
    surahNumberPlaceholder: "No. Surat",
    invalidSurahNumber: "Masukkan nomor surat yang valid (1-114).",
    searchDuaPlaceholder: "Cari doa atau grup...",
    filterByCategory: "Filter berdasarkan kategori",
    viewDetail: "Lihat Detail",
    source: "Sumber",
    tags: "Tag",
    backToListDua: "Kembali ke Daftar Doa",
    searchSurahPlaceholder: "Cari surat (nama/nomor)...",
    noResultsFound: "Surat tidak ditemukan.",
    searchCityPlaceholder: "Cari kota...",
    backToCityList: "Kembali ke Daftar Kota",
    dailySchedule: "Jadwal Harian",
    monthlySchedule: "Jadwal Bulanan",
    date: "Tanggal",
    imsak: "Imsak",
    subuh: "Subuh",
    terbit: "Terbit",
    dhuha: "Dhuha",
    dzuhur: "Dzuhur",
    ashar: "Ashar",
    maghrib: "Maghrib",
    isya: "Isya",
    dataProvidedBy: "Data jadwal sholat oleh",
    hadith_books: "Koleksi Hadits",
    hadiths_available: "{count} Hadits Tersedia",
    view_hadiths: "Lihat Hadits",
    back_to_book_list: "Kembali ke Daftar Kitab",
    search_hadith_placeholder: "Cari hadits...",
    batch_size: "Per Halaman",
    page_x_of_y: "Halaman {x} dari {y}",
    prev: "Sebelumnya",
    next: "Berikutnya",
    hadith_number: "Hadits No. {number}",
    search: "Cari",
    go_to_page: "Buka Halaman",
    zakatCalculator: "Kalkulator Zakat",
    zakatType: "Jenis Zakat",
    zakatFitrah: "Zakat Fitrah",
    zakatMal: "Zakat Mal (Harta)",
    zakatIncome: "Zakat Penghasilan (Profesi)",
    zakatAgriculture: "Zakat Pertanian",
    zakatTrade: "Zakat Perdagangan",
    zakatLivestock: "Zakat Hewan Ternak",
    calculate: "Hitung",
    result: "Hasil",
    numberOfPeople: "Jumlah Jiwa (Orang)",
    ricePricePerKg: "Harga Beras per kg (Opsional)",
    totalWealth: "Total Harta (Tabungan, Emas, dll.)",
    goldPricePerGram: "Harga Emas per Gram Saat Ini",
    nisabValue: "Nilai Nisab",
    monthlyIncome: "Pendapatan per Bulan",
    monthlyExpenses: "Pengeluaran Pokok per Bulan",
    harvestResultKg: "Hasil Panen (kg)",
    pricePerKg: "Harga Jual per kg",
    irrigationType: "Jenis Irigasi",
    rainFed: "Tadah Hujan / Alami (Zakat 10%)",
    paidIrrigation: "Irigasi Berbayar (Zakat 5%)",
    tradeAssets: "Aset Lancar (Stok Barang)",
    workingCapital: "Modal Kerja",
    receivables: "Piutang Lancar",
    shortTermDebt: "Hutang Jangka Pendek",
    livestockType: "Jenis Ternak",
    camel: "Unta",
    cow: "Sapi / Kerbau",
    goat: "Kambing / Domba",
    numberOfAnimals: "Jumlah Ekor",
    zakatDue: "Zakat Wajib Dikeluarkan",
    zakatNotDue: "Belum Wajib Mengeluarkan Zakat",
    belowNisab: "Total harta Anda di bawah ambang batas (nisab).",
    nisabInfo: "Nisab adalah batas minimum harta yang wajib dizakati. Untuk emas, nisabnya adalah 85 gram.",
    nisabIncomeInfo: "Nisab penghasilan dihitung per bulan, setara dengan nilai 1/12 dari 85 gram emas.",
    nisabAgricultureInfo: "Nisab untuk hasil pertanian adalah 653 kg gabah atau 520 kg beras.",
    enterGoldPrice: "Mohon masukkan harga emas untuk menghitung nisab.",
    zakatAmount: "Jumlah Zakat",
    totalZakatFitrah: "Total Zakat Fitrah",
    or: "atau",
    kgOfRice: "kg Beras",
    livestockZakatInfo: "Zakat ternak memiliki perhitungan khusus berdasarkan jumlah dan jenis hewan.",
    login: "Masuk",
    loggingIn: "Masuk...",
    register: "Daftar",
    registering: "Mendaftar...",
    logout: "Keluar",
    username: "Nama Pengguna",
    password: "Kata Sandi",
    email: "Email",
    confirmPassword: "Konfirmasi Kata Sandi",
    usernamePlaceholder: "Masukkan nama pengguna",
    emailPlaceholder: "Masukkan email",
    passwordPlaceholder: "Masukkan kata sandi",
    confirmPasswordPlaceholder: "Konfirmasi kata sandi",
    emailInUse: "Email sudah digunakan.",
    userNotFound: "Pengguna tidak ditemukan.",
    incorrectPassword: "Kata sandi salah.",
    passwordsDoNotMatch: "Kata sandi tidak cocok.",
    registerSuccess: "Pendaftaran berhasil! Anda sekarang masuk.",
    welcomeUser: "Selamat datang, {user}!",
    haveAccount: "Sudah punya akun?",
    noAccount: "Belum punya akun?",
    inheritanceCalculator: "Kalkulator Waris (Faraidh)",
    totalEstate: "Total Harta (Tirkah)",
    estateLiabilities: "Hak-Hak Terkait Harta",
    heirs: "Ahli Waris",
    results: "Hasil Perhitungan",
    step1: "Langkah 1: Harta",
    step2: "Langkah 2: Hak-hak",
    step3: "Langkah 3: Ahli Waris",
    step4: "Langkah 4: Hasil",
    assetRelatedDebt: "Hutang terkait harta (cth: gadai)",
    nonAssetRelatedDebt: "Hutang tidak terkait harta (pinjaman)",
    funeralExpenses: "Biaya penyelenggaraan jenazah",
    bequest: "Wasiat (Maks 1/3 Harta)",
    totalLiabilities: "Total Hak-hak",
    netEstate: "Harta Waris Siap Bagi (Irs)",
    nextStep: "Langkah Berikutnya",
    prevStep: "Kembali",
    calculateInheritance: "Hitung Warisan",
    reset: "Ulangi",
    heir: "Ahli Waris",
    share: "Bagian",
    amount: "Jumlah Diterima",
    error_totalEstateRequired: "Total harta wajib diisi.",
    error_invalidPositiveNumber: "Input tidak valid, masukkan angka positif.",
    error_inputCannotBeNegative: "Input tidak boleh negatif.",
    warning_bequestAdjusted: "Wasiat melebihi 1/3, disesuaikan otomatis.",
    error_liabilitiesExceedEstate: "Hak-hak melebihi total harta, tidak valid.",
    warning_netEstateNegative: "Harta waris negatif, disetel ke 0.",
    error_mustBeInteger: "Input harus angka bulat non-negatif.",
    warning_heirCountTooLarge: "Jumlah ahli waris terlalu besar, periksa kembali.",
    error_noValidHeirs: "Tidak ada ahli waris yang berhak menurut syariat.",
    warning_rounding: "Harta tersisa {amount} karena pembulatan.",
    error_calculation: "Terjadi kesalahan perhitungan, hasil disetel ke 0.",
    son: "Anak Laki-Laki",
    daughter: "Anak Perempuan",
    grandson_from_son: "Cucu Laki dari Anak Laki",
    granddaughter_from_son: "Cucu Perempuan dari Anak Laki",
    father: "Bapak",
    mother: "Ibu",
    husband: "Suami",
    wife: "Istri",
    paternal_grandfather: "Kakek (dari Bapak)",
    paternal_grandmother: "Nenek (Ibu dari Bapak)",
    maternal_grandmother: "Nenek (Ibu dari Ibu)",
    full_brother: "Saudara Kandung",
    full_sister: "Saudari Kandung",
    paternal_brother: "Saudara Sebapak",
    paternal_sister: "Saudari Sebapak",
    maternal_brother: "Saudara Seibu",
    maternal_sister: "Saudari Seibu",
    full_nephew: "Putra dari Saudara Kandung",
    paternal_nephew: "Putra dari Saudara Sebapak",
    full_paternal_uncle: "Paman Sekandung",
    paternal_uncle: "Paman Sebapak",
    full_paternal_cousin: "Putra dari Paman Sekandung",
    paternal_cousin: "Putra dari Paman Sebapak",
    male_emancipator: "Pria yang Memerdekakan",
    female_emancipator: "Wanita yang Memerdekakan",
    summary: "Ringkasan",
    distributionChart: "Grafik Pembagian",
    blocked: "Terhalang"
  },
  en:{
    enableReminders:"Enable Reminders", addHabit:"Add Habit", export:"Export", import:"Import",
    todayProgress:"Today’s Progress", view:"View", tips:"Tips",
    tipText:"Group habits into categories. Click a chapter in the directory to quick-filter.",
    checklist:"Checklist", name:"Name", type:"Type", frequency:"Frequency", daily:"Daily", weekly:"Weekly",
    monthly:"Monthly", yearly:"Yearly", special:"Special (specific dates)", reminderTime:"Reminder Time",
    reminderHint:"Allow browser notifications.", days:"Days (Weekly)", dayOfMonth:"Day(s) of Month",
    monthDay:"Month & Day (Yearly)", specificDates:"Specific Dates", notes:"Notes",
    save:"Save", saving:"Saving...", noItems:"No habits yet.", periodDaily:"Today’s period",
    periodWeekly:"This week period (ISO Week)", periodMonthly:"This month period", periodYearly:"This year period",
    periodSpecial:"Specific date", edit:"Edit", streak:"Streak", best:"Best",
    wajib: "Wajib", sunnah: "Sunnah", allCategories: "— All Categories —",
    searchPlaceholder: "Search…", deleteConfirm: "Delete this habit?",
    importSuccess: "Import successful.", importFailed: "Import failed: ", invalidFile: "Invalid file",
    remindersEnabled: "Reminders enabled. Keep this tab open.", permissionDenied: "Notification permission denied.",
    browserNotSupported: "Browser does not support Notification API.", modalTitleAdd: "Add Habit", modalTitleEdit: "Edit Habit",
    categoryExample: "e.g., Rituals/Prayer or Etiquette/Eating", subCategoryHint: "Use “/” for sub-chapters.",
    domExample: "Example: 1,15,30", datesExample: "YYYY-MM-DD; YYYY-MM-DD",
    notesPlaceholder: "Add intentions, targets, references...", namePlaceholder: "Example: Fajr Prayer",
    directory: "Directory (Chapters & Etiquette)", directoryHint: "Use nested categories, e.g., Etiquette/Eating or Household/Marriage.",
    history: "History", completionHistory: "Completion History", noCompletions: "No completions yet.", completedOn: "Completed on",
    targetStreak: "Target Streak", reminders: "Reminders", enableReminder: "Enable reminder for this habit",
    reminderDays: "Reminder Days", reminderDaysHint: "Leave unchecked for all days.", allDays: "All Days", streakGoalReached: "Streak Goal Reached!",
    streakGoalReachedBody: "Congratulations! You've reached your {target}-day streak goal for {habitName}.",
    theme: "Theme", light: "Light", dark: "Dark",
    editCategory: "Edit Category", editCategoryPrompt: "Enter new name for '{oldPath}':",
    categoryRenameSuccess: "Category renamed successfully.", other: "Other",
    otherFeatures: "Other Features", quran: "Read Quran", hadith: "Read Hadith", zakat: "Zakat Calculator", prayerTimes: "Prayer Times", qibla: "Qibla Direction", duas: "Du'a & Dhikr",
    editTitle: "Edit Title", saveContent: "Save Content", editModule: "Edit Module", title: "Title", content: "Content",
    moduleContentPlaceholder: "You can add your own notes, links, or personal content here...",
    analytics: "Analytics", progressDashboard: "Progress Dashboard", selectHabit: "Select a Habit to Analyze",
    overallProgress: "Overall Progress (Daily)", completionRateLast30Days: "Completion Rate (Last 30 Days)",
    streakTrendLast30Days: "Streak Trend (Last 30 Days)", completions: "Completions",
    noDataForChart: "Not enough data to display chart.",
    analyticsInfo: "Analytics are now available for all habit frequencies.",
    timePeriod: "Time Period", last30Days: "30 Days", last90Days: "90 Days", last365Days: "1 Year",
    completionHeatmap: "Completion Heatmap", streakHistory: "Streak History",
    streakLength: "Streak Length", endedOn: "Ended On", notCompleted: "Not Completed",
    selectHabitFirst: "Select a habit to see its details.",
    due: "Due", completed: "Completed", missed: "Missed",
    contentSaved: "Content saved!",
    useHijriCalendar: "Use Hijri Calendar", hijriBased: "Hijri-based",
    dayOfMonthHijri: "Day(s) of Month (Hijri)", monthAndDayHijri: "Month & Day(s) (Hijri)",
    monthHijri: "Month (Hijri)",
    selectSurah: "Select Surah",
    loading: "Loading...",
    errorFetching: "Failed to fetch data. Please try again.",
    revelation_makkah: "Meccan",
    revelation_madinah: "Medinan",
    verses: "verses",
    reminderDayOfMonth: "Reminder Day(s) of Month",
    reminderMonthDay: "Reminder Month & Day(s)",
    backToList: "Back to Surah List",
    goTo: "Go",
    surahNumberPlaceholder: "Surah No.",
    invalidSurahNumber: "Please enter a valid surah number (1-114).",
    searchDuaPlaceholder: "Search for dua or group...",
    filterByCategory: "Filter by category",
    viewDetail: "View Detail",
    source: "Source",
    tags: "Tags",
    backToListDua: "Back to Dua List",
    searchSurahPlaceholder: "Search surah (name/no.)...",
    noResultsFound: "No surah found.",
    searchCityPlaceholder: "Search city...",
    backToCityList: "Back to City List",
    dailySchedule: "Daily Schedule",
    monthlySchedule: "Monthly Schedule",
    date: "Date",
    imsak: "Imsak",
    subuh: "Fajr",
    terbit: "Sunrise",
    dhuha: "Dhuha",
    dzuhur: "Dhuhr",
    ashar: "Asr",
    maghrib: "Maghrib",
    isya: "Isha",
    dataProvidedBy: "Prayer time data provided by",
    hadith_books: "Hadith Collections",
    hadiths_available: "{count} Hadiths Available",
    view_hadiths: "View Hadiths",
    back_to_book_list: "Back to Book List",
    search_hadith_placeholder: "Search hadith...",
    batch_size: "Per Page",
    page_x_of_y: "Page {x} of {y}",
    prev: "Prev",
    next: "Next",
    hadith_number: "Hadith No. {number}",
    search: "Search",
    go_to_page: "Go to Page",
    zakatCalculator: "Zakat Calculator",
    zakatType: "Zakat Type",
    zakatFitrah: "Zakat al-Fitr",
    zakatMal: "Zakat al-Mal (Wealth)",
    zakatIncome: "Zakat on Income (Profession)",
    zakatAgriculture: "Zakat on Agriculture",
    zakatTrade: "Zakat on Trade",
    zakatLivestock: "Zakat on Livestock",
    calculate: "Calculate",
    result: "Result",
    numberOfPeople: "Number of People",
    ricePricePerKg: "Price of Rice per kg (Optional)",
    totalWealth: "Total Wealth (Savings, Gold, etc.)",
    goldPricePerGram: "Current Gold Price per Gram",
    nisabValue: "Nisab Value",
    monthlyIncome: "Monthly Income",
    monthlyExpenses: "Essential Monthly Expenses",
    harvestResultKg: "Harvest Result (kg)",
    pricePerKg: "Sale Price per kg",
    irrigationType: "Irrigation Type",
    rainFed: "Rain-fed / Natural (10% Zakat)",
    paidIrrigation: "Paid Irrigation (5% Zakat)",
    tradeAssets: "Current Assets (Stock)",
    workingCapital: "Working Capital",
    receivables: "Receivables",
    shortTermDebt: "Short-term Debt",
    livestockType: "Livestock Type",
    camel: "Camel",
    cow: "Cow / Buffalo",
    goat: "Goat / Sheep",
    numberOfAnimals: "Number of Animals",
    zakatDue: "Zakat Due",
    zakatNotDue: "Zakat Not Due",
    belowNisab: "Your total wealth is below the nisab threshold.",
    nisabInfo: "Nisab is the minimum amount of wealth that must be owned before zakat becomes obligatory. For gold, the nisab is 85 grams.",
    nisabIncomeInfo: "The nisab for income is calculated monthly, equivalent to the value of 1/12 of 85 grams of gold.",
    nisabAgricultureInfo: "The nisab for agricultural produce is 653 kg of grain or 520 kg of rice.",
    enterGoldPrice: "Please enter the gold price to calculate the nisab.",
    zakatAmount: "Zakat Amount",
    totalZakatFitrah: "Total Zakat al-Fitr",
    or: "or",
    kgOfRice: "kg of Rice",
    livestockZakatInfo: "Zakat for livestock has specific calculations based on the type and number of animals.",
    login: "Login",
    loggingIn: "Logging in...",
    register: "Register",
    registering: "Registering...",
    logout: "Logout",
    username: "Username",
    password: "Password",
    email: "Email",
    confirmPassword: "Confirm Password",
    usernamePlaceholder: "Enter username",
    emailPlaceholder: "Enter email",
    passwordPlaceholder: "Enter password",
    confirmPasswordPlaceholder: "Confirm password",
    emailInUse: "Email is already in use.",
    userNotFound: "User not found.",
    incorrectPassword: "Incorrect password.",
    passwordsDoNotMatch: "Passwords do not match.",
    registerSuccess: "Registration successful! You are now logged in.",
    welcomeUser: "Welcome, {user}!",
    haveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    inheritanceCalculator: "Inheritance Calculator (Faraidh)",
    totalEstate: "Total Estate (Tirkah)",
    estateLiabilities: "Estate-Related Liabilities",
    heirs: "Heirs",
    results: "Calculation Results",
    step1: "Step 1: Estate",
    step2: "Step 2: Liabilities",
    step3: "Step 3: Heirs",
    step4: "Step 4: Results",
    assetRelatedDebt: "Asset-related debt (e.g., mortgage)",
    nonAssetRelatedDebt: "Non-asset-related debt (loans)",
    funeralExpenses: "Funeral Expenses",
    bequest: "Bequest (Max 1/3 of Estate)",
    totalLiabilities: "Total Liabilities",
    netEstate: "Net Estate for Inheritance (Irs)",
    nextStep: "Next Step",
    prevStep: "Previous Step",
    calculateInheritance: "Calculate Inheritance",
    reset: "Reset",
    heir: "Heir",
    share: "Share",
    amount: "Amount Received",
    error_totalEstateRequired: "Total estate is required.",
    error_invalidPositiveNumber: "Invalid input, please enter a positive number.",
    error_inputCannotBeNegative: "Input cannot be negative.",
    warning_bequestAdjusted: "Bequest exceeds 1/3, adjusted automatically.",
    error_liabilitiesExceedEstate: "Liabilities exceed total estate, which is not valid.",
    warning_netEstateNegative: "Net estate is negative, set to 0.",
    error_mustBeInteger: "Input must be a non-negative integer.",
    warning_heirCountTooLarge: "Heir count seems too large, please double-check.",
    error_noValidHeirs: "No valid heirs according to Islamic law.",
    warning_rounding: "A remainder of {amount} exists due to rounding.",
    error_calculation: "A calculation error occurred, results set to 0.",
    son: "Son",
    daughter: "Daughter",
    grandson_from_son: "Son's Son",
    granddaughter_from_son: "Son's Daughter",
    father: "Father",
    mother: "Mother",
    husband: "Husband",
    wife: "Wife",
    paternal_grandfather: "Paternal Grandfather",
    paternal_grandmother: "Paternal Grandmother",
    maternal_grandmother: "Maternal Grandmother",
    full_brother: "Full Brother",
    full_sister: "Full Sister",
    paternal_brother: "Paternal Brother",
    paternal_sister: "Paternal Sister",
    maternal_brother: "Maternal Brother",
    maternal_sister: "Maternal Sister",
    full_nephew: "Full Brother's Son",
    paternal_nephew: "Paternal Brother's Son",
    full_paternal_uncle: "Full Paternal Uncle",
    paternal_uncle: "Paternal Half-Uncle",
    full_paternal_cousin: "Full Paternal Uncle's Son",
    paternal_cousin: "Paternal Half-Uncle's Son",
    male_emancipator: "Male Emancipator",
    female_emancipator: "Female Emancipator",
    summary: "Summary",
    distributionChart: "Distribution Chart",
    blocked: "Blocked"
  }
};

export const FREQUENCY_OPTIONS: { value: HabitFrequency; labelKey: string }[] = [
    { value: 'daily', labelKey: 'daily' },
    { value: 'weekly', labelKey: 'weekly' },
    { value: 'monthly', labelKey: 'monthly' },
    { value: 'yearly', labelKey: 'yearly' },
    { value: 'special', labelKey: 'special' }
];

export const DAY_OF_WEEK_OPTIONS = [
    { value: 1, label: 'Sen' }, { value: 2, label: 'Sel' }, { value: 3, label: 'Rab' },
    { value: 4, label: 'Kam' }, { value: 5, label: 'Jum' }, { value: 6, label: 'Sab' }, { value: 0, label: 'Min' }
];

export const DEFAULT_MODULES = [
  { id: 'quran', icon: '📖', defaultTitleKey: 'quran', customTitles: {}, content: {} },
  { id: 'hadith', icon: '📜', defaultTitleKey: 'hadith', customTitles: {}, content: {} },
  { id: 'zakat', icon: '💸', defaultTitleKey: 'zakatCalculator', customTitles: {}, content: {} },
  { id: 'inheritance', icon: '⚖️', defaultTitleKey: 'inheritanceCalculator', customTitles: {}, content: {} },
  { id: 'prayer_times', icon: '⏰', defaultTitleKey: 'prayerTimes', customTitles: {}, content: {} },
  { id: 'qibla', icon: '🕋', defaultTitleKey: 'qibla', customTitles: {}, content: {} },
  { id: 'duas', icon: '🤲', defaultTitleKey: 'duas', customTitles: {}, content: {} },
];

export const HIJRI_MONTHS = {
  id: ["Muharram","Safar","Rabi'ul Awal","Rabi'ul Akhir","Jumadil Awal","Jumadil Akhir","Rajab","Sya'ban","Ramadhan","Syawal","Dzulqa'dah","Dzulhijjah"],
  en: ["Muharram","Safar","Rabi' al-awwal","Rabi' al-thani","Jumada al-ula","Jumada al-thani","Rajab","Sha'ban","Ramadan","Shawwal","Dhu al-Qi'dah","Dhu al-Hijjah"]
};
